name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npx ng build --base-href "https://togglight.derveydylan.github.io/" --output-path=../derveydylan.github.io/togglight

      - name: Add CNAME file
        run: echo "togglight.derveydylan.github.io" > ../derveydylan.github.io/togglight/CNAM

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../derveydylan.github.io/togglight

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        run: |
          cd ../derveydylan.github.io
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add togglight
          git commit -m "Deploy togglight"
          git pus